### ISSUE TITLE
Error: `option.outputDir` should not empty;TypeError: Cannot read property 'packageInfo' of undefined;

### ISSUE THREAD

**Issue by ProgramAlgo** [aliyun/darabonba-java-generator#38]
Following the tutorial, Something went wrong
 [https://github.com/aliyun/darabonba/blob/master/doc/getting_started.md](https://github.com/aliyun/darabonba/blob/master/doc/getting_started.md)

#### 1.  Error: `option.outputDir` should not empty

Darafile:
``` json
{
  "scope": "hello",
  "name": "hello",
  "version": "1.0.0",
  "main": "./hello.dara",
}
```
``` bash
dara codegen java ./tmp
```

``` javascript
Error: `option.outputDir` should not empty
at new Visitor (/usr/local/lib/node_modules/@darabonba/cli/node_modules/@darabonba/java-generator/lib/generator.js:102:13)
```

may be missing **"package"** in Darafile file

#### 2. TypeError: Cannot read property 'packageInfo' of undefined

Darafile:
```
{
  "scope": "hello",
  "name": "hello",
  "version": "1.0.0",
  "main": "./hello.dara",
  "package": "hello",
}
```

```
dara codegen java ./tmp
```

```
TypeError: Cannot read property 'packageInfo' of undefined
at new Visitor (/usr/local/lib/node_modules/@darabonba/cli/node_modules/@darabonba/java-generator/lib/generator.js:111:36)
```
may be missing **"java"** in Darafile file

The correct Darafile is: 
```
{
"scope": "hello",
"name": "hello",
"version": "1.0.0",
"main": "./hello.dara",
"package": "hello",
"java": {}
}
```

#### 3. Some spelling problems were found when trying to find the parameters in "java"

**"licenseNmae"**: Unknown word.

``` javascript
  const needParamsKeys = ['description', 'url',
    'licenseNmae', 'developerId',
    'licenseUrl', 'developerName',
    'developerEmail', 'scmConnection',
    'scmDeveloperConnection', 'scmUrl', 'groupId',
    'artifactId', 'version'
  ];
```

**"tamplate"**: Unknown word.

**Comment by atptro** [comment]
You can use the following configuration
{
	"scope": "hello",
	"name": "hello",
	"version": "1.0.0",
	"main": "./hello.dara",
	"package": "hello",
	"java": {
		"package": "xxxxxxxxx",
		"packageInfo": {
			"description": "xxxxxxxxx",
			"url": "xxxxxxxxx",
			"licenseNmae": "xxxxxxxxx",
			"licenseUrl": "xxxxxxxxx",
			"developerId": "xxxxxxxxx",
			"developerName": "xxxxxxxxx",
			"developerEmail": "xxxxxxxxx"
		}
	}
}

**Comment by atptro** [comment]
You can use the following configuration
`{
	"scope": "hello",
	"name": "hello",
	"version": "1.0.0",
	"main": "./hello.dara",
	"package": "hello",
	"java": {
		"package": "xxxxxxxxx",
		"packageInfo": {
			"description": "xxxxxxxxx",
			"url": "xxxxxxxxx",
			"licenseNmae": "xxxxxxxxx",
			"licenseUrl": "xxxxxxxxx",
			"developerId": "xxxxxxxxx",
			"developerName": "xxxxxxxxx",
			"developerEmail": "xxxxxxxxx"
		}
	}
}`

**Comment by atptro** [comment]
```xml
{
	"scope": "hello",
	"name": "hello",
	"version": "1.0.0",
	"main": "./hello.dara",
	"package": "hello",
	"java": {
		"package": "xxxxxxxxx",
		"packageInfo": {
			"description": "xxxxxxxxx",
			"url": "xxxxxxxxx",
			"licenseNmae": "xxxxxxxxx",
			"licenseUrl": "xxxxxxxxx",
			"developerId": "xxxxxxxxx",
			"developerName": "xxxxxxxxx",
			"developerEmail": "xxxxxxxxx"
		}
	}
}
```

**Comment by atptro** [comment]
You can use the following configuration
```xml
{
	"scope": "hello",
	"name": "hello",
	"version": "1.0.0",
	"main": "./hello.dara",
	"package": "hello",
	"java": {
		"package": "xxxxxxxxx",
		"packageInfo": {
			"description": "xxxxxxxxx",
			"url": "xxxxxxxxx",
			"licenseNmae": "xxxxxxxxx",
			"licenseUrl": "xxxxxxxxx",
			"developerId": "xxxxxxxxx",
			"developerName": "xxxxxxxxx",
			"developerEmail": "xxxxxxxxx"
		}
	}
}
```
